"""Render preserved blog content and the homepage guide carousel.

Content in blogs/content.json is the September 27 live-site import. Do not rewrite
source_html or the visible titles during design changes. Rendering adjusts only
links, local images, heading hierarchy, and heading IDs; article text is preserved.
"""
from pathlib import Path
from html import escape, unescape
from html.parser import HTMLParser
from build_subproducts import ROUTES
from build_locations import ROUTES as LOCATION_ROUTES
import json
import re

ROOT = Path(__file__).resolve().parent
LIVE = 'https://www.beautifulblindsandshades.com'
POSTS = json.loads((ROOT / 'blogs/content.json').read_text())
ASSETS = json.loads((ROOT / 'blogs/assets.json').read_text())
INDEX = json.loads((ROOT / 'blogs/index-metadata.json').read_text())
START = '<!-- Homepage guides: generated by build_blogs.py -->'
END = '<!-- End homepage guides -->'

TOPICS = {
 'blackout-window-treatments-bluffton-homes': ('Light & privacy', '/products/shades', 'Explore custom shades'),
 'plantation-shutters-for-columbia-city-homes': ('Shutters', '/products/plantation-shutters', 'Explore plantation shutters'),
 'energy-efficient-blinds-leo-cedarville-indiana-homes': ('Energy efficiency', '/products/shades', 'Compare window shades'),
 'best-window-blinds-new-construction-homes-huntertown-indiana': ('Blinds', '/products/blinds', 'Explore custom blinds'),
 'motorized-zebra-shades-fort-wayne-light-control': ('Motorization', '/products/shades', 'Explore custom shades'),
 'custom-roller-shades-fort-wayne-open-concept-homes': ('Shades', '/products/shades', 'Explore custom shades'),
 'outdoor-patio-shades-guild-fort-wayne': ('Outdoor living', '/services/outdoor-shades', 'Explore outdoor shades'),
 'save-energy-window-treatments-fort-wayne': ('Energy efficiency', '/products/shades', 'Compare window shades'),
 'fort-wayne-window-treatments-guide': ('Buying guides', '/#products', 'Compare window treatments'),
 '5-ways-custom-blinds-and-shades-can-transform-your-fort-wayne-home': ('Design ideas', '/products/blinds', 'Explore custom blinds'),
 'cellular-shades-fort-wayne-energy-savings': ('Energy efficiency', '/products/shades', 'Explore custom shades'),
 'motorized-blinds-and-shades-in-fort-wayne': ('Motorization', '/products/shades', 'Explore custom shades'),
}
FALLBACK_IMAGES = {
 'blackout-window-treatments-bluffton-homes': '/assets/roller-shades-fort-wayne-indiana.jpg',
 'plantation-shutters-for-columbia-city-homes': '/assets/wood-plantation-shutters-fort-wayne-indiana.jpg',
}
DESCRIPTION_FIXES = {
 'plantation-shutters-for-columbia-city-homes': 'Explore plantation shutters for Columbia City homes, including wood and composite materials, light control, custom fitting, and installation.',
 'motorized-zebra-shades-fort-wayne-light-control': 'Learn how motorized zebra shades adjust light and privacy in Fort Wayne homes, with fabric choices, controls, and installation considerations.',
}
BUILT = {'/', '/blogs', '/contact', '/products/blinds', '/products/shades', '/products/plantation-shutters', '/services/outdoor-shades', '/services/blind-shade-repair', '/services/blind-and-shade-cleaning', '/services/window-treatments'} | {'/blog-post/' + p['slug'] for p in POSTS} | ROUTES | LOCATION_ROUTES


def image_for(post):
    return ASSETS.get(post['image'].get('src'), FALLBACK_IMAGES.get(post['slug']))


def strip_text(html):
    class Text(HTMLParser):
        def __init__(self):
            super().__init__(convert_charrefs=True)
            self.parts = []
        def handle_data(self, text):
            self.parts.append(text)
    parser = Text()
    parser.feed(html)
    return ' '.join(''.join(parser.parts).split())


def article_body(post):
    body = post['source_html']
    # Preserve the words in the additional source H1; correct its structural level.
    body = re.sub(r'<(/?)h1\b', r'<\1h2', body)
    def href(match):
        value = unescape(match[1])
        path = value.removeprefix(LIVE)
        if path == '/shades/cellular-shades':
            path = '/custom-shades-fort-wayne-indiana/cellular-shades-fort-wayne-indiana'
        # Existing contact-ghl remains on the live site until that route is migrated.
        if path.startswith('/') and not path.startswith('//'):
            if path.split('#')[0].rstrip('/') in BUILT or path == '/':
                value = path
            else:
                value = LIVE + path
        return 'href="' + escape(value, quote=True) + '"'
    body = re.sub(r'href="([^"]*)"', href, body)
    def img(match):
        tag = match[0]
        for remote, local in ASSETS.items():
            tag = tag.replace(remote, local)
        tag = re.sub(r'\s(?:srcset|sizes|width|height)="[^"]*"', '', tag)
        if 'loading=' not in tag:
            tag = tag.replace('<img', '<img loading="lazy"')
        return tag
    body = re.sub(r'<img\b[^>]*>', img, body)
    headings = []
    def heading(match):
        level, attrs, words = match.groups()
        anchor = 'guide-section-' + str(len(headings) + 1)
        headings.append((int(level), anchor, strip_text(words)))
        attrs = re.sub(r'\s+id="[^"]*"', '', attrs)
        return f'<h{level}{attrs} id="{anchor}">{words}</h{level}>'
    body = re.sub(r'<h([2-6])([^>]*)>(.*?)</h\1>', heading, body, flags=re.S)
    assert strip_text(body) == post['source_text'], 'Article wording changed: ' + post['slug']
    return body, headings


def card(post, heading=3):
    title = escape(post['card_title'])
    topic = escape(TOPICS[post['slug']][0])
    return f'''<article class="guide-card"><a href="/blog-post/{post['slug']}" class="guide-card-link"><div class="guide-card-photo"><img src="{image_for(post)}" alt="" width="640" height="420" loading="lazy"></div><div class="guide-card-copy"><span class="guide-topic">{topic}</span><h{heading}>{title}</h{heading}><span class="guide-read" aria-hidden="true">Read the guide <span>→</span></span></div></a></article>'''


def homepage_with_guides(home):
    cards = '\n'.join(card(p) for p in POSTS)
    section = f'''{START}
    <section class="section home-guides" id="guides" aria-labelledby="guides-title"><div class="container guides-container">
      <div class="guides-heading"><div><p class="eyebrow">Ideas for your windows</p><h2 id="guides-title">Window treatment guides</h2><p>Explore blinds, shades, and shutters, with advice for homes in Fort Wayne and nearby communities.</p></div><a class="text-link" href="/blogs">View all guides</a></div>
      <div class="guide-carousel" aria-label="Window treatment guides"><div class="guide-track" id="home-guide-track" tabindex="0" aria-label="Browse all 12 guides">{cards}</div>
      <div class="guide-carousel-footer"><span class="guide-count" role="status" aria-live="polite">12 guides for your home</span><div class="guide-controls" hidden><button type="button" class="guide-prev" aria-label="Previous guides" aria-controls="home-guide-track"><svg viewBox="0 0 24 24" width="22" height="22" fill="none" stroke="currentColor" stroke-width="2.2" aria-hidden="true"><path d="m14 6-6 6 6 6"/></svg></button><button type="button" class="guide-next" aria-label="Next guides" aria-controls="home-guide-track"><svg viewBox="0 0 24 24" width="22" height="22" fill="none" stroke="currentColor" stroke-width="2.2" aria-hidden="true"><path d="m10 6 6 6-6 6"/></svg></button></div></div></div>
    </div></section>
    {END}'''
    if START in home:
        home = home[:home.index(START)] + section + home[home.index(END) + len(END):]
    else:
        home = home.replace('    <section class="section consultation"', section + '\n    <section class="section consultation"', 1)
    if 'href="/blog.css' not in home:
        home = home.replace('</head>', '<link rel="stylesheet" href="/blog.css?v=20260928-buttons">\n<script src="/guides.js?v=20260927-guides-3" defer></script>\n</head>')
    return home


def shared_paths(html):
    html = html.replace('src="assets/', 'src="/assets/').replace('href="./"', 'href="/"')
    return re.sub(r'href="#(products|meet-david|service-area|reviews|guides)"', r'href="/#\1"', html).replace('href="#consultation"','href="/contact"')


def shell(home, title, description, path, content, schema, image=None):
    head = home[home.index('<head>'):home.index('</head>') + len('</head>')]
    head = re.sub(r'<title>.*?</title>', '<title>' + escape(title) + '</title>', head)
    head = re.sub(r'<meta name="description"[^>]+>', '<meta name="description" content="' + escape(description, quote=True) + '">', head)
    head = head.replace('rel="canonical" href="' + LIVE + '/"', 'rel="canonical" href="' + LIVE + path + '"')
    head = re.sub(r'\s*<link rel="preload"[^>]*>', '', head)
    head = head.replace('href="assets/', 'href="/assets/').replace('href="styles.css', 'href="/styles.css').replace('src="script.js', 'src="/script.js')
    social = f'<meta property="og:type" content="{"article" if path.startswith("/blog-post/") else "website"}"><meta property="og:title" content="{escape(title,quote=True)}"><meta property="og:description" content="{escape(description,quote=True)}"><meta property="og:url" content="{LIVE + path}">'
    if image:
        social += '<meta property="og:image" content="' + LIVE + image + '">'
    head = head.replace('</head>', social + '\n<script type="application/ld+json">' + json.dumps(schema).replace('</','<\\/') + '</script>\n</head>')
    header = shared_paths(home[home.index('  <header class="header">'):home.index('  <main')])
    footer = shared_paths(home[home.index('  <footer class="footer">'):])
    return '<!doctype html>\n<html lang="en">\n' + head + '\n<body class="blog-page"><a class="skip" href="#main">Skip to content</a>\n' + header + '<main id="main">\n' + content + '\n</main>\n' + footer


def blog_outputs(home):
    listing = '''<section class="blog-index-intro"><div class="container"><nav class="blog-breadcrumb" aria-label="Breadcrumb"><a href="/">Home</a><span aria-hidden="true">/</span><span aria-current="page">Guides</span></nav><h1>Window treatment guides</h1><p>Ideas, product comparisons, and local advice from Beautiful Blinds &amp; Shades. Find a starting point for your windows.</p></div></section><section class="section guide-library" aria-label="All window treatment guides"><div class="container"><div class="guide-library-heading"><p>All 12 guides</p><a class="text-link" href="/#products">Explore our window treatments</a></div><div class="guide-grid">'''
    listing += '\n'.join(card(p, heading=2) for p in POSTS) + '</div></div></section>'
    graph = {'@context':'https://schema.org','@type':'CollectionPage','@id':LIVE+'/blogs#page','url':LIVE+'/blogs','name':'Window treatment guides','mainEntity':{'@type':'ItemList','itemListElement':[{'@type':'ListItem','position':i+1,'url':p['url'],'name':p['title']} for i,p in enumerate(POSTS)]}}
    yield ROOT/'dist/blogs/index.html', shell(home,INDEX['title'],INDEX['description'],'/blogs',listing,graph)
    for p in POSTS:
        body, headings = article_body(p)
        topic, product, product_label = TOPICS[p['slug']]
        main_level = min((h[0] for h in headings), default=2)
        toc = ''.join(f'<li><a href="#{anchor}">{escape(text)}</a></li>' for level,anchor,text in headings if level==main_level and text)
        description = DESCRIPTION_FIXES.get(p['slug'], p['original_description'])
        image = image_for(p)
        # Use the existing public H1 for the title tag, replacing the old raw slug.
        title = p['title']
        alt = p['image'].get('alt','') if p['slug'] not in FALLBACK_IMAGES else ('Roller shades at living room windows' if 'blackout' in p['slug'] else 'Wood plantation shutters in a living room')
        article = f'''<article><header class="article-header"><div class="container"><nav class="blog-breadcrumb" aria-label="Breadcrumb"><a href="/">Home</a><span aria-hidden="true">/</span><a href="/blogs">Guides</a><span aria-hidden="true">/</span><span aria-current="page">{escape(topic)}</span></nav><p class="eyebrow">{escape(topic)}</p><h1>{escape(p['title'])}</h1><p class="article-byline">Beautiful Blinds &amp; Shades</p></div></header><div class="container article-cover"><img src="{image}" alt="{escape(alt,quote=True)}" fetchpriority="high"></div><div class="container article-layout"><div class="article-main"><details class="article-contents"><summary>In this guide</summary><ol>{toc}</ol></details><div class="article-body">{body}</div></div><aside class="article-help" aria-label="Window treatment consultation"><p class="eyebrow">See it in your home</p><h2>Let’s talk about<br>your windows.</h2><p>Compare samples and get help choosing treatments for your home.</p><a class="button" href="/contact">Free Consultation</a><a class="text-link" href="tel:+12602226467">Call (260) 222-6467</a><a class="article-product-link" href="{product}">{product_label}</a></aside></div></article>'''
        related = [q for q in POSTS if q['slug'] != p['slug']]
        related.sort(key=lambda q: 0 if TOPICS[q['slug']][1]==product else 1)
        article += '<section class="section related-guides" aria-labelledby="related-title"><div class="container"><div class="guides-heading"><h2 id="related-title">More guides for your home</h2><a class="text-link" href="/blogs">View all guides</a></div><div class="guide-grid">'+''.join(card(q) for q in related[:3])+'</div></div></section>'
        schema = {'@context':'https://schema.org','@graph':[{'@type':'BlogPosting','@id':p['url']+'#article','mainEntityOfPage':p['url'],'url':p['url'],'headline':p['title'],'description':description,'image':LIVE+image,'author':{'@type':'Organization','name':'Beautiful Blinds & Shades','url':LIVE+'/'},'publisher':{'@id':LIVE+'/#business'},'inLanguage':'en-US'}, {'@type':'BreadcrumbList','itemListElement':[{'@type':'ListItem','position':1,'name':'Home','item':LIVE+'/'},{'@type':'ListItem','position':2,'name':'Guides','item':LIVE+'/blogs'},{'@type':'ListItem','position':3,'name':p['title'],'item':p['url']}]}]}
        yield ROOT/'dist/blog-post'/p['slug']/'index.html',shell(home,title,description,'/blog-post/'+p['slug'],article,schema,image)
